version: "3.8"
services:
  transmissionbot:
    build: .
    container_name: transmissionbot
    environment:
      - TZ=UTC
    volumes:
      - ./config.json:/app/config.json
      - ./transfers.json:/app/transfers.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python bot.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
