version: '3.4'  # Ensure you are using version 3.4 or above

services:
  transmissionbot:
    build:
      context: /volume1/docker/transmissionbot
      dockerfile: Dockerfile
    container_name: transmissionbot
    network_mode: synobridge  # Attach the service to the custom bridge network, see https://drfrankenstein.co.uk/step-3-setting-up-a-docker-bridge-network-in-container-manager/
    environment:
      - PUID=1057 #CHANGE_TO_YOUR_UID
      - PGID=65543 #CHANGE_TO_YOUR_GID
      - TZ=America/Denver #CHANGE_TO_YOUR_TZ
      - PYTHONUNBUFFERED=1
    volumes:
      - /volume1/docker/transmissionbot/data:/data
      - /volume1/docker/transmissionbot/src:/src
    restart: unless-stopped